### ISSUE TITLE
[Feat] API 부가적인 기능 완성

### ISSUE THREAD

**Issue by arinming** [Cherrypickk/CherryPick-Android#124]
## 설명
부가적인 기능을 추가합니다.

## To-Do List
- [x] 유저네임a를 모두 서버에서 받아오기
- [x] 기사 리스트를 끝까지 스크롤 했을 때 새로운 기사 받기
- [x] 최근 검색어 클릭 이벤트
- [x] 엔터 값 입력도 최근 검색어에 추가
- [x] 기사 불러오는 로딩중 화면 추가
