### ISSUE TITLE
[Feat] icon, string, color, typo 설정

### ISSUE THREAD

**Issue by arinming** [Cherrypickk/CherryPick-Android#35]
## 설명
디자인을 참고하여 아이콘, 폰트, 색상, 텍스트를 정리합니다.

## To-Do List
- [x] icon을 svg파일로 받아서 vector로 변환하기
- [x] 적용 폰트 세팅하기
- [x] 모든 문자열을 string 리소스로 저장
- [x] 모든 컬러값을 color 리소스로 저장
