### ISSUE TITLE
[Feat] 뉴스 기능 구현

### ISSUE THREAD

**Issue by arinming** [Cherrypickk/CherryPick-Android#51]
## 설명
뉴스 페이지의 전체적인 기능을 구현합니다.

## To-Do List
- [x] 좋아요, 공유 버튼 구현
- [x] 뉴스 아이템을 클릭했을 때 해당 뉴스 페이지로 이동
- [x] 최근 검색어 삭제 구현
- [x] 스크랩시 스낵바 구현
