### ISSUE TITLE
[Feat] 스크랩 레이아웃 구현

### ISSUE THREAD

**Issue by arinming** [Cherrypickk/CherryPick-Android#52]
## 설명
스크랩 프래그먼트의 레이아웃을 구현합니다.

## To-Do List
- [x] 스크랩한 기사가 없을 때의 레이아웃 구현
- [x] 스크랩한 기사가 있을 때의 레이아웃 구현
- [x] 스크랩 삭제 구현
- [ ] 스크랩한 기사가 있고, 없을 때 판별
- [ ] 스크랩한 기사 개수 판별
